# Generated by Django 4.1.7 on 2023-03-28 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialization',
            name='title',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
