# Generated by Django 4.1.7 on 2023-03-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(blank=True, max_length=255, verbose_name='Full_name')),
                ('email', models.EmailField(blank=True, max_length=255, unique=True, verbose_name='Email')),
                ('image', models.ImageField(blank=True, upload_to='user_images')),
                ('position', models.CharField(blank=True, max_length=100)),
                ('place_of_work', models.CharField(blank=True, max_length=255)),
                ('about_me', models.CharField(blank=True, max_length=4096)),
                ('help', models.CharField(blank=True, max_length=4096)),
                ('level_mentor', models.CharField(blank=True, max_length=2048)),
                ('experience', models.CharField(blank=True, max_length=10)),
                ('skills', models.CharField(blank=True, max_length=512)),
                ('status', models.BooleanField(default=True)),
                ('price', models.CharField(blank=True, max_length=10)),
                ('language', models.CharField(blank=True, max_length=20)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('activation_code', models.CharField(blank=True, max_length=8)),
                ('specialization', models.ManyToManyField(blank=True, related_name='mentor_specialization', to='base.specialization')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
