# Generated by Django 4.1.7 on 2023-03-13 16:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_level', models.CharField(choices=[('FR', 'Junior'), ('MD', 'Midle'), ('SR', 'Senior')], default='FR', max_length=2)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=13, null=True)),
                ('description', models.TextField()),
                ('create_at', models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 13, 22, 21, 41, 160726))),
            ],
        ),
        migrations.CreateModel(
            name='ResponseStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField()),
                ('denied', models.BooleanField()),
                ('message', models.CharField(blank=True, max_length=500, null=True)),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='res_statement', to='statement.statement')),
            ],
        ),
    ]
