# Generated by Django 4.1.7 on 2023-03-26 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='my_level',
            field=models.CharField(max_length=10),
        ),
    ]
